services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  post-db:
    image: postgres:16
    container_name: post-db
    environment:
      POSTGRES_USER: ${POST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${POST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${POST_POSTGRES_DB}
    ports:
      - "${POST_POSTGRES_PORT}:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
  post_db_data:
